lib/cadeau_platform_web/router.ex
defmodule CadeauPlatformWeb.Router do
  use CadeauPlatformWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CadeauPlatform.Plugs.CurrentUser
    plug CadeauPlatform.Plugs.Cart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CadeauPlatformWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    get "/login", SessionController , :new
    post "/login", SessionController , :create
    delete "/logout", SessionController , :delete
    resources "/shopping_cart", ShoppingCartController
    post "/shopping_cart/add", ShoppingCartController, :add
    resources "/order", OrderController
    post "/order/create_order", OrderController, :create_order
  end

  # Other scopes may use custom stacks.
  # scope "/api", CadeauPlatformWeb do
  #   pipe_through :api
  # end
end

lib/cadeau_platform_web/views/layout_view.ex
defmodule CadeauPlatformWeb.LayoutView do
  use CadeauPlatformWeb, :view
end

lib/cadeau_platform_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadeau</title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </head>

  <body>
    <div class="container">
      <%= if !!(get_flash(@conn, :info)) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>

      <%= if !!(get_flash(@conn, :error)) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <%= if @user_id do %>
        <%= link "Logout", to: session_path(@conn, :delete), method: :delete %>
      <% else %>
        <%= link "Login", to: session_path(@conn, :create) %>
      <% end %>

      <div>
        <%= link "View Products", to: page_path(@conn, :index) %>
      </div>

      <%= if @user_id && !Kernel.is_nil(@cart_id) do %>
        <div>
          <%= link "Shopping Cart", to: shopping_cart_path(@conn, :index) %>
        </div>
      <% end %>

      <%= if @user_id do %>
        <div>
          <%= link "View My Orders", to: order_path(@conn, :index) %>
        </div>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>